=head1 This is the first test advent calendar post

=head1 DESCRIPTION

This is a post about how great Dancer is.

Well, actually, it's just a placeholder test article; the real articles will,
hopefully, be a substantially better read than this!

=head1 AUTHOR

David Precious <davidp@preshweb.co.uk>


