=head1 Map the Way with Dancer::Plugin::SiteMap

I was sitting staring at yet another XML site map document when it came
to me; It should be easier than this!

Enter L<Dancer::Plugin::SiteMap> - The easy way to map.

=head2 So How Does It Work?

Simplicity itself:

    use Dancer;
    use Dancer::Plugin::SiteMap;

That's it! Your Dancer App now has C</sitemap> and C</sitemap.xml>
routes.

=head2 What's In Store For The Future?

Eventually I'd like to add support for optional custom template of
the HTML SiteMap. 

=head2 Author

This article has been written by James Ronan C<< <james@ronanweb.co.uk> >> for
the Perl Dancer Advent Calendar 2010.

